import tkinter as tk
win = tk.Tk()
win.title("")
win.geometry('300x200')
menubar = tk.Menu(win)
win.config(menu = menubar)
file_menu = tk.Menu(menubar)
menubar.add_cascade(label = "檔案", menu = file_menu)
edit_menu = tk.Menu(menubar)
menubar.add_cascade(label = "編輯", menu = edit_menu)
run_menu = tk.Menu(menubar)
menubar.add_cascade(label = "執行", menu =run_menu)
window_menu = tk.Menu(menubar)
menubar.add_cascade(label = "視窗", menu = window_menu)
online_menu = tk.Menu(menubar)
menubar.add_cascade(label = "線上說明", menu = online_menu)
win.mainloop()
