#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"
  https://create.arduino.cc/cloud/things/7f764f78-264f-45bc-9f69-e857825b47b1 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int illuminance;
  int opening;
  int opening_demand;
  bool manually;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <Servo.h>
#define servo_pin  D1

Servo servo1;
void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  servo1.attach(servo_pin);
  servo1.write(0);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
  

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  delay(2000);
  illuminance = map(analogRead(A0), 0, 1023, 100, 0);
  Serial.print("Illuminance =");
  Serial.println(illuminance);
  if (!manually) {
    opening = 100 - illuminance;
    servo1.write(map(opening, 0, 100, 0, 90));
  }
}
void onManuallyChange()  {

}
void onOpeningDemandChange()  {
  if (manually) {
    opening = opening_demand;
    servo1.write(map(opening, 0, 100, 0, 90));
  } 
}



