// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "a1607742-b3f2-4441-b650-f5035d47b6a8";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onOpeningDemandChange();
void onManuallyChange();

int illuminance;
int opening;
int opening_demand;
bool manually;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(illuminance, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(opening, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(opening_demand, READWRITE, ON_CHANGE, onOpeningDemandChange);
  ArduinoCloud.addProperty(manually, READWRITE, ON_CHANGE, onManuallyChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
