tupleScore=(89,87,36,55,94)
tupleName=("小明","小華","小強","小保","小呆")
print("****DTC大學-學生績表****")
print("姓名\t分數")
print("=======================")
for i in range(len(tupleScore)):
    print("%s\t%d" %(tupleName[i], tupleScore[i]))
print("=======================")
print("  最高分：%d" %max(tupleScore))
print("  最低分：%d" %min(tupleScore))
print("平均分數：%.2f" %(sum(tupleScore)/len(tupleScore)))