//------------------------------------------------------------------------------
// <auto-generated>
//     此程式碼由工具產生。
//     執行庫版本:2.0.50727.1433
//
//     對此文件的修改可能會導致不正確的行為，而且如果
//     重新產生程式碼，這些修改將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 使用LINQ技術統計員工的工資總額.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=db_11;User ID=sa")]
        public string db_11ConnectionString {
            get {
                return ((string)(this["db_11ConnectionString"]));
            }
        }
    }
}
