#!/usr/bin/perl

# Print useage of the program
if(@ARGV == 0){
  die <<Usage_str;
   Usage: bin2hex <infile> <outfile>
Usage_str
}
else {
   $file_in  = $ARGV[0];
   $file_out = $ARGV[1];
}

# convert binary to text file
open(fh_in, "od -An -tx1 -v -w4 $file_in | ");
open(fh_out, ">$file_out") or die "Error: cannot open output file: $file_out ";
     

while(<fh_in>) {
  chomp $_;
  $_ =~ s/ //g;
  printf fh_out "$_\n";
}

