//------------------------------------------------------------------------------
// <auto-generated>
//     此程式碼由工具產生。
//     執行庫版本:2.0.50727.1433
//
//     對此文件的修改可能會導致不正確的行為，而且如果
//     重新產生程式碼，這些修改將遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMTP協議發送電子郵件.Properties
{


    /// <summary>
    ///   一個強類型的資源類，用於尋找本地化的字串等。
    /// </summary>
    // 此類是由 StronglyTypedResourceBuilder
    // 類透過類似於 ResGen 或 Visual Studio 的工具自動產生的。
    // 若要新增或刪除成員，請編輯 .ResX 文件，然後重新執行 ResGen
    // (以 /str 作為命令選項)，或重新產生 VS 項目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   傳回此類使用的、快取的 ResourceManager 實例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMTP協議發送電子郵件.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   為所有資源尋找重新寫入目前線程的 CurrentUICulture 屬性，
        ///   方法是使用此強類型資源類。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
    }
}
