// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "a1607742-b3f2-4441-b650-f5035d47b6a8";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onCloseChange();
void onFullChange();
void onHalfChange();

String opening_status;
bool close;
bool full;
bool half;
bool ls_close;
bool ls_full;
bool ls_half;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(opening_status, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(close, READWRITE, ON_CHANGE, onCloseChange);
  ArduinoCloud.addProperty(full, READWRITE, ON_CHANGE, onFullChange);
  ArduinoCloud.addProperty(half, READWRITE, ON_CHANGE, onHalfChange);
  ArduinoCloud.addProperty(ls_close, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(ls_full, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(ls_half, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
