//------------------------------------------------------------------------------
// <auto-generated>
//     此代碼由工具產生。
//     執行庫版本:2.0.50727.1433
//
//     對此檔案修改可能會導致不正常的結果，如果
//     重新生成代碼，這些更改將會丟失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduallyWindows.Properties {
    using System;
    
    
    /// <summary>
    ///   強類型資源類，用於查找本地化字符串等。
    /// </summary>
    // 此類別是由 StronglyTypedResourceBuilder
    // 類別透過類似 ResGen 或 Visual Studio 的工具自動產生的。
    // 若要新增或刪除成員，請編輯 .ResX 檔案，然後重新執行 ResGen
    // (以 /str 作為命令選項
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此類使用的緩存 ResourceManager 實例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GraduallyWindows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   為使用此強類型資源類的所有資源查找
        ///   重寫當前線程的 CurrentUICulture 屬性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Long {
            get {
                object obj = ResourceManager.GetObject("Long", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap XP右 {
            get {
                object obj = ResourceManager.GetObject("XP右", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
