import tkinter as tk
def fnSet(img):
    lblPhoto.config(image=img)
    
win = tk.Tk()
win.title('相簿')
win.geometry('250x230')
imgPhoto1=tk.PhotoImage(file='sheep1.png')
imgPhoto2=tk.PhotoImage(file='cat.png')
imgPhoto3=tk.PhotoImage(file='sheep2.png')
imgPhoto1_s=imgPhoto1.subsample(4,4)
imgPhoto2_s=imgPhoto2.subsample(4,4)
imgPhoto3_s=imgPhoto3.subsample(4,4)
lblPhoto=tk.Label(win,image=imgPhoto1)
lblPhoto.pack()
lfrmSet=tk.LabelFrame(win,text='選擇照片',relief='raised',borderwidth=2)
lfrmSet.pack()
btn1=tk.Button(lfrmSet,image=imgPhoto1_s,command=lambda:fnSet(imgPhoto1))
btn1.pack(side='left',padx=5)
btn2=tk.Button(lfrmSet,image=imgPhoto2_s,command=lambda:fnSet(imgPhoto2))
btn2.pack(side='left',padx=5)
btn3=tk.Button(lfrmSet,image=imgPhoto3_s,command=lambda:fnSet(imgPhoto3))
btn3.pack(side='left',padx=5)
win.mainloop()

