#!C:\Winpython\basedir35\build\winpython-32bit-3.5.x.2\python-3.5.2\python.exe

print("""
The 'bokeh-server' command from versions 0.10 and earlier no longer exists.
Please see the documentation for the new 'bokeh' command here:

  http://bokeh.pydata.org/en/latest/docs/user_guide/cli.html
""")
