import tkinter as tk
win=tk.Tk()
win.geometry('200x200')
win.title('grid配置')
win.rowconfigure(0,weight=1)
win.rowconfigure(1,weight=1)
win.rowconfigure(2,weight=1)
win.columnconfigure(0,weight=1)
win.columnconfigure(1,weight=1)
win.columnconfigure(2,weight=1)
lbl1=tk.Label(win, text = '北',font=('標楷體', 40))
lbl2=tk.Label(win, text = '東',font=('標楷體', 40),bg='yellow')
lbl3=tk.Label(win, text = '西',font=('標楷體', 40),bg='lightgreen')
lbl4=tk.Label(win, text = '中',font=('標楷體', 40),bg='pink')
lbl5=tk.Label(win, text = '南',font=('標楷體', 40),bg='lightblue')
lbl1.grid(row=0,column=0,columnspan=2,sticky='nswe')
lbl2.grid(row=0,column=2,rowspan=2,sticky='nswe')
lbl3.grid(row=1,column=0,rowspan=2,sticky='nswe')
lbl4.grid(row=1,column=1,sticky='nswe')
lbl5.grid(row=2,column=1,columnspan=2,sticky='nswe')
win.mainloop()
