import tkinter as tk
win=tk.Tk()
win.geometry('300x200')
win.title('pack配置')
win.configure(bg='white')
lbl1=tk.Label(win, text = '元件版面配置',font=('微軟正黑體', 16),fg='white',bg='blue')
lbl2=tk.Label(win, text = '方法',font=('標楷體', 12))
lbl3=tk.Label(win, text = 'pack()方法',font=('標楷體', 12),bg='lightgreen')
lbl4=tk.Label(win, text = 'grid()方法',font=('標楷體', 12),bg='pink')
lbl5=tk.Label(win, text = 'place()方法',font=('標楷體', 12),bg='lightblue')
lbl1.pack(fill='x')
lbl2.pack(side='left', fill='y')
lbl3.pack(pady=5, fill='both', expand=True)
lbl4.pack(pady=5, fill='both', expand=True)
lbl5.pack(pady=5, fill='both', expand=True)
win.mainloop()
