//------------------------------------------------------------------------------
// <auto-generated>
//     此代碼由工具產生。
//     執行庫版本:2.0.50727.1433
//
//     對此檔案修改可能會導致不正常的結果，如果
//     重新產生代碼，這些修改將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuHistory.Properties
{


    /// <summary>
    ///   一個強固類型的資源類別，用於尋找本地化的字串等。
    /// </summary>
    // 此類別是由 StronglyTypedResourceBuilder
    // 類別透過類似 ResGen 或 Visual Studio 的工具自動產生的。
    // 若要新增或刪除成員，請編輯 .ResX 檔案，然後重新執行 ResGen
    // (以 /str 作為命令選項
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder","2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance","CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   傳回此類別使用的、快取的 ResourceManager 實例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MenuHistory.Properties.Resources",typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   為所有資源尋找重新寫入目前線程的 CurrentUICulture 屬性，
        ///   方法是使用此強固類型資源類別。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
    }
}
