import numpy as np 

a = np.array([[1,2],[3,4]])
print("a=")
print(a)
s = np.array([[5,6],[7,8]])
print("s=")
print(s)
b = np.add(a, s)       
print("np.add(a,s)=")
print(b)    
b = np.subtract(a, s)       
print("np.subtract(a,s)=")
print(b)   
b = np.multiply(a, s)       
print("np.multiply(a,s)=")
print(b)  
b = np.divide(a, s)       
print("np.divide(a,s)=")
print(b)  