# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsunit',
            name='catego',
            field=models.CharField(max_length=10),
        ),
    ]
