import pandas as pd

df1 = pd.DataFrame({"key":["a","b","b"],"data1":range(3)})  
df2 = pd.DataFrame({"key":["a","b","c"],"data2":range(3)})  
print(df1)
df1.to_html("ch8-4-4b-01.html")
print("---------------------------")
print(df2)
df2.to_html("ch8-4-4b-02.html")
print("---------------------------")
df3 = pd.merge(df1, df2)
print(df3)
df3.to_html("ch8-4-4b-03.html")
print("---------------------------")
df4 = pd.merge(df2, df1)
print(df4)
df4.to_html("ch8-4-4b-04.html")
print("---------------------------")
df5 = pd.merge(df2, df1, how='left')
print(df5)
df5.to_html("ch8-4-4b-05.html")