//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace vcs_DiskDirectoryFile1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string doc_foldername {
            get {
                return ((string)(this["doc_foldername"]));
            }
            set {
                this["doc_foldername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string video_player_path {
            get {
                return ((string)(this["video_player_path"]));
            }
            set {
                this["video_player_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string search_path {
            get {
                return ((string)(this["search_path"]));
            }
            set {
                this["search_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool flag_check_filesize_min {
            get {
                return ((bool)(this["flag_check_filesize_min"]));
            }
            set {
                this["flag_check_filesize_min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1234")]
        public int filesize_max {
            get {
                return ((int)(this["filesize_max"]));
            }
            set {
                this["filesize_max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4500")]
        public int filesize_min {
            get {
                return ((int)(this["filesize_min"]));
            }
            set {
                this["filesize_min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flag_find_big_files {
            get {
                return ((bool)(this["flag_find_big_files"]));
            }
            set {
                this["flag_find_big_files"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flag_find_small_files {
            get {
                return ((bool)(this["flag_find_small_files"]));
            }
            set {
                this["flag_find_small_files"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string git_foldername {
            get {
                return ((string)(this["git_foldername"]));
            }
            set {
                this["git_foldername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flag_check_filesize_max {
            get {
                return ((bool)(this["flag_check_filesize_max"]));
            }
            set {
                this["flag_check_filesize_max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flag_search_folders_all {
            get {
                return ((bool)(this["flag_search_folders_all"]));
            }
            set {
                this["flag_search_folders_all"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flag_search_folders_empty {
            get {
                return ((bool)(this["flag_search_folders_empty"]));
            }
            set {
                this["flag_search_folders_empty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flag_search_folders_small {
            get {
                return ((bool)(this["flag_search_folders_small"]));
            }
            set {
                this["flag_search_folders_small"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flag_find_good_files {
            get {
                return ((bool)(this["flag_find_good_files"]));
            }
            set {
                this["flag_find_good_files"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flag_find_same_files0 {
            get {
                return ((bool)(this["flag_find_same_files0"]));
            }
            set {
                this["flag_find_same_files0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flag_find_same_files1 {
            get {
                return ((bool)(this["flag_find_same_files1"]));
            }
            set {
                this["flag_find_same_files1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flag_find_same_files2 {
            get {
                return ((bool)(this["flag_find_same_files2"]));
            }
            set {
                this["flag_find_same_files2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool flag_find_same_files3 {
            get {
                return ((bool)(this["flag_find_same_files3"]));
            }
            set {
                this["flag_find_same_files3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string search_foldernames {
            get {
                return ((string)(this["search_foldernames"]));
            }
            set {
                this["search_foldernames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public int lv_file_cw0 {
            get {
                return ((int)(this["lv_file_cw0"]));
            }
            set {
                this["lv_file_cw0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("110")]
        public int lv_file_cw1 {
            get {
                return ((int)(this["lv_file_cw1"]));
            }
            set {
                this["lv_file_cw1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("110")]
        public int lv_file_cw2 {
            get {
                return ((int)(this["lv_file_cw2"]));
            }
            set {
                this["lv_file_cw2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700")]
        public int lv_file_cw3 {
            get {
                return ((int)(this["lv_file_cw3"]));
            }
            set {
                this["lv_file_cw3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public int lv_video_cw0 {
            get {
                return ((int)(this["lv_video_cw0"]));
            }
            set {
                this["lv_video_cw0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int lv_video_cw1 {
            get {
                return ((int)(this["lv_video_cw1"]));
            }
            set {
                this["lv_video_cw1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int lv_video_cw2 {
            get {
                return ((int)(this["lv_video_cw2"]));
            }
            set {
                this["lv_video_cw2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("110")]
        public int lv_video_cw3 {
            get {
                return ((int)(this["lv_video_cw3"]));
            }
            set {
                this["lv_video_cw3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("110")]
        public int lv_video_cw4 {
            get {
                return ((int)(this["lv_video_cw4"]));
            }
            set {
                this["lv_video_cw4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700")]
        public int lv_video_cw5 {
            get {
                return ((int)(this["lv_video_cw5"]));
            }
            set {
                this["lv_video_cw5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int lv_dir_cw0 {
            get {
                return ((int)(this["lv_dir_cw0"]));
            }
            set {
                this["lv_dir_cw0"] = value;
            }
        }
    }
}
