clear all;
t=linspace(0, 2*pi);
r=10;
x=r*cos(t);
y=r*sin(t);
a=r*[cos(0.50*pi), sin(0.50*pi)];
b=r*[cos(0.90*pi), sin(0.90*pi)];
c=r*[cos(1.25*pi), sin(1.25*pi)];
d=r*[cos(1.80*pi), sin(1.80*pi)];
plot(x, y, 'b', a(1), a(2), '.k', b(1), b(2), '.k', c(1), c(2), '.k', d(1), d(2), '.k');
axis image
text(a(1), a(2), ' A');
text(b(1), b(2), ' B');
text(c(1), c(2), ' C');
text(d(1), d(2), ' D');
line([a(1), b(1)], [a(2), b(2)], 'color', 'r'); t=(a+b)/2; text(t(1), t(2), 'AB');
line([b(1), c(1)], [b(2), c(2)], 'color', 'r'); t=(b+c)/2; text(t(1), t(2), 'BC');
line([c(1), d(1)], [c(2), d(2)], 'color', 'r'); t=(c+d)/2; text(t(1), t(2), 'CD');
line([d(1), a(1)], [d(2), a(2)], 'color', 'r'); t=(d+a)/2; text(t(1), t(2), 'DA');
line([a(1), c(1)], [a(2), c(2)], 'color', 'r'); t=(a+c)/2; text(t(1), t(2), 'AC');
line([b(1), d(1)], [b(2), d(2)], 'color', 'r'); t=(b+d)/2; text(t(1), t(2), 'BD');
ab=norm(a-b);
bc=norm(b-c);
cd=norm(c-d);
ad=norm(a-d);
ac=norm(a-c);
bd=norm(b-d);
fprintf('ab = %f\n', ab);
fprintf('bc = %f\n', bc);
fprintf('cd = %f\n', cd);
fprintf('ad = %f\n', ad);
fprintf('ac = %f\n', ac);
fprintf('bd = %f\n', bd);
fprintf('ab*cd = %f\n', ab*cd);
fprintf('ad*bc = %f\n', ad*bc);
fprintf('ac*bd = %f\n', ac*bd);
fprintf('ab*cd+ad*bc-ac*bd = %f\n', ab*cd+ad*bc-ac*bd);