a = 1
print("變數a型態 = " + str(type(a)))
b = str(a)
print("str(a)型態 = " + str(type(b)))
c = 55.22
print("變數c型態 = " + str(type(c)))
d = str(c)
print("str(c)型態 = " + str(type(d)))
e = int(c)
print("int(c)型態 = " + str(type(e)))
f = "1234"
print("變數f型態 = " + str(type(f)))
g = int(f)
print("int(f)型態 = " + str(type(g)))
h = "12.45"
print("變數h型態 = " + str(type(h)))
i = float(h)
print("float(h)型態 = " + str(type(i)))
